-- MySQL Script generated by MySQL Workbench
-- sáb 30 jul 2022 18:18:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering


-- -----------------------------------------------------
-- Schema tecno_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema tecno_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `tecno_db` ;
USE `tecno_db` ;

-- -----------------------------------------------------
-- Table `tecno_db`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name_and_surname` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `country` VARCHAR(100) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phone` VARCHAR(45) NOT NULL,
  `image` VARCHAR(1024) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles1_idx` (`role_id`),
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`role_id`)
    REFERENCES `tecno_db`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`user_cards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`user_cards` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Tarjetas_de_Usuario_Usuarios1_idx` (`user_id`),
  CONSTRAINT `fk_Tarjetas_de_Usuario_Usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tecno_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`purchases`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`purchases` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `purchase_date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Compras_Usuarios1_idx` (`user_id`),
  CONSTRAINT `fk_Compras_Usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tecno_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`invoice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`invoice` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `user_id` INT NOT NULL,
  `value` INT NOT NULL,
  `purchase_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Factura_Usuarios1_idx` (`user_id`),
  INDEX `fk_Factura_Compras1_idx` (`purchase_id`),
  CONSTRAINT `fk_Factura_Usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tecno_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Factura_Compras1`
    FOREIGN KEY (`purchase_id`)
    REFERENCES `tecno_db`.`purchases` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `category_name` VARCHAR(100) NOT NULL,
  `category_image` varchar(200) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `brand` VARCHAR(100) NOT NULL,
  `price` INT NOT NULL,
  `discount` INT NOT NULL,
  `description` TEXT(500) NOT NULL,
  `stock` TINYINT NOT NULL,
  `category_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productos_Categorias1_idx` (`category_id`),
  CONSTRAINT `fk_Productos_Categorias1`
    FOREIGN KEY (`category_id`)
    REFERENCES `tecno_db`.`categories` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`invoice_detail`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`invoice_detail` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `invoice_id` INT NOT NULL,
  `number_of_installments` INT NOT NULL,
  `installment_amount` SMALLINT NOT NULL,
  `products_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Detalle_de_Factura_Factura1_idx` (`invoice_id`),
  INDEX `fk_Detalle_de_Factura_Productos1_idx` (`products_id`),
  CONSTRAINT `fk_Detalle_de_Factura_Factura1`
    FOREIGN KEY (`invoice_id`)
    REFERENCES `tecno_db`.`invoice` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Detalle_de_Factura_Productos1`
    FOREIGN KEY (`products_id`)
    REFERENCES `tecno_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`product_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`product_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Imagenes_del_Producto_Productos1_idx` (`product_id`),
  CONSTRAINT `fk_Imagenes_del_Producto_Productos1`
    FOREIGN KEY (`product_id`)
    REFERENCES `tecno_db`.`products` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`products_cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`products_cart` (
  `id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  `quantity` SMALLINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Productos_en_Carrito_Productos1_idx` (`product_id`),
  INDEX `fk_Productos_en_Carrito_Usuarios1_idx` (`user_id`),
  CONSTRAINT `fk_Productos_en_Carrito_Productos1`
    FOREIGN KEY (`product_id`)
    REFERENCES `tecno_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Productos_en_Carrito_Usuarios1`
    FOREIGN KEY (`user_id`)
    REFERENCES `tecno_db`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `tecno_db`.`product_financing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `tecno_db`.`product_financing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `installment_amount` MEDIUMINT NOT NULL,
  `number_of_installments` TINYINT NOT NULL,
  `product_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Financiacion_del_Producto_Productos1_idx` (`product_id`),
  CONSTRAINT `fk_Financiacion_del_Producto_Productos1`
    FOREIGN KEY (`product_id`)
    REFERENCES `tecno_db`.`products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
